name: docker_demo_009_CICD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build_develop:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      working-directory: ./DockerDemo009/
      run: dotnet restore
    - name: Build
      working-directory: ./DockerDemo009/
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./DockerDemo009/
      run: dotnet test --no-build --verbosity normal
