name: docker_demo_009_CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_to_heroku:

    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check out code
      working-directory: ./DockerDemo009/
      env: 
        HEROKU_SECRET: ${{ secrets.HEROKU_SECRET }}
        APP_NAME: ${{ 'dockerdemo009' }}
      run: |
        docker build -t docker_demo_009 .
        docker tag docker_demo_009 registry.heroku.com/$APP_NAME/web
        docker login --username=_ --password=$HEROKU_SECRET registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
